### ISSUE TITLE
(may or may not be a feature already) is it possible to add support for continuity like Lazurite did with Embeddium 0.2.X

### ISSUE THREAD

**Issue by hiimrickross** [txnimc/xenon#1]
### Request Description

I went ahead to replace all the Embeddium things with Xenon, but on loading I realized it wasn't working with Lazurite because Lazurite requested only 0.2.X Embeddium. And Lazurite is needed for Continuity's connected textures to work when using Oculus etc etc. and not Optifine. I later couldn't even load due to a nullpointerexception initializing game, but that's another ticket issue.

**Comment by txnitxnichopper** [comment]
Latest version of Lazurite works with Embeddium/Xenon 0.3.x and Continuity

**Comment by hiimrickross** [comment]
> Latest version of Lazurite works with Embeddium/Xenon 0.3.x and Continuity

thank you, i tested it just now and my game is working ok! (0.3.5 xenon, latest lazurite an continuity)
