### ISSUE TITLE
seem to crash initializing game after replacing 0.2.16 embeddium setup with xenon 0.3.1 + oculus ver 15.5 latest

### ISSUE THREAD

**Issue by hiimrickross** [txnimc/xenon#2]
### Bug Description

First off with 0.3.4 xenon i loaded up into mc but entering the world crashed with a big mixins error.

so i thought ok, oculus 15 says it only goes up to 3.3 of embeddium so maybe that's why, so I tried xenon 031 but then it just crashes in loading now with the same kind of error.

prior to changing, my game worked with embeddium 0.2.16, embeddiumplus v1.2.2, lazurite 1.0.1, oculus 1.6.13, rubidium extras 0.5.3.1, and textrues options 0.1.3. I removed all of these for oculus 15.5 and xenon.

### Reproduction Steps

Replaced the mods, loaded the game, crash.

### Log File

[crash-2024-02-25_09.30.41-client.txt](https://github.com/anthxnymc/xenon/files/14394659/crash-2024-02-25_09.30.41-client.txt)

**Comment by itsdeadfrosty** [comment]
pretty much similar situation here

[crash-2024-02-25_16.43.32-client.txt](https://github.com/anthxnymc/xenon/files/14397945/crash-2024-02-25_16.43.32-client.txt)

**Comment by txnitxnichopper** [comment]
please update to latest versions, it is working on Xenon 0.3.5 and Oculus 1.6.15a

**Comment by hiimrickross** [comment]
> please update to latest versions, it is working on Xenon 0.3.5 and Oculus 1.6.15a

thank you veyr much i tried it again and my game is loading into the world now. Im still not too sure on the differences between swapping from the old setup of "embedium, embeddiumplus, lazurite, oculus, rubidium-extras, textrues-embeddium options" vs xenon, lazu, oculus... But everything seems to be working OK.

One concern I had was that I saw in Github changelog for Embeddium that on 0.3.1 (or 2) update it said that Entity Texture Features and Entity Model Features might be broken when updating to/beyond that point. Is that resolved or was it a non-issue?

Is it also possible for Embeddium++ https://www.curseforge.com/minecraft/mc-mods/embeddiumplus/comments to work with this Xenon setup? Or is it not needed? Emb++ errors because it needs Textrues Options which are now integrated into Xenon.
