### ISSUE TITLE
Smooth lighting level for xenon like optifine

### ISSUE THREAD

**Issue by GreytheDegod** [txnimc/xenon#3]
### Request Description

I really want the smooth lighting level feature and I really love Xenon it's a great mod
I want to keep the ambient occlusion at 50% but i really have no idea how to do it I tried doing it with texture packs but i failed
So I really want you to make this a feature in Xenon

**Comment by Tapacywka** [comment]
Use Royamic Lights (Lamd Dynamic Light fork) with Embeddium instead of Xenon.

**Comment by txnitxnichopper** [comment]
Ambient occlusion can be controlled with shaders. As for the lack of the slider in Sodium, refer to https://github.com/FlashyReese/sodium-extra-fabric/issues/125
