### ISSUE TITLE
Error during loading  with newest Create

### ISSUE THREAD

**Issue by WordStormRose** [txnimc/xenon#9]
### Bug Description

When loading the newest Curseforge version of Xenon with the newest version of Create, I get the following message before getting to the main menu:

Mod flywheel only supports embeddium _0.3.25 or above_
Currently, embeddium is _0.3.19+mc1.20.1_

### Reproduction Steps

Have both Create and Xenon in the same mod profile and try to load the game.

### Log File

[latest.log](https://github.com/user-attachments/files/16861593/latest.log)

**Comment by muppetenergy** [comment]
i'm getting this as well, create closed their ticket about it 
[crash-2024-09-04_06.46.06-fml.txt](https://github.com/user-attachments/files/16871608/crash-2024-09-04_06.46.06-fml.txt)
[latest.log](https://github.com/user-attachments/files/16871621/latest.log)

**Comment by katubug** [comment]
I also have this issue.

**Comment by YumatanGames** [comment]
Same issue here.

**Comment by loti1234** [comment]
ig xenon just hasn't updated to newest embeddium ver yet

**Comment by Amateur233** [comment]
im pretty sure xenon's embeddium stub hasn't updated
therefore, the dependency issue

**Comment by txnitxnichopper** [comment]
should be updated.
